name: Docs

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Requirements
      run: |
        sudo apt-get install build-essential meson doxygen sphinx-doc
        sudo python3 -m pip install furo breathe exhale sphinx-sitemap
    - name: Checkout repo
      uses: actions/checkout@1.0.0
    - name: Configure
      run: meson setup build -Ddocs=true
    - name: Build docs
      run: |
        meson compile -C build docs/sphinx
        cd build/docs/sphinx
        touch .nojekyll
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build/docs/sphinx # The folder the action should deploy.
